[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared", package = "shared" }
anyhow = "1.0.100"
bevy = { version = "0.17.3", features = ["dynamic_linking"] }
serde = "1.0.228"
serde_json = "1.0.149"
tokio = "1.49.0"
