[workspace]
members = ["shared", "server", "client"]
resolver = "2"

# We put shared profiles here so they apply to all three crates
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3