[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", features = ["dynamic_linking"] }
serde = "1.0.228"
serde_json = "1.0.148"
pathfinding = "4.14.0" 
anyhow = "1.0.100"
thiserror = "2.0.17"
